# Generated by Django 3.2.1 on 2022-10-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221028_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
    ]
