# Generated by Django 3.2.1 on 2022-10-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
