# Generated by Django 3.2.1 on 2022-10-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
