# Generated by Django 3.2.1 on 2022-10-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='describtion',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
