# Generated by Django 3.2.1 on 2022-10-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='describtion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
