# Generated by Django 3.2.1 on 2022-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_describtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
