# Generated by Django 3.2.1 on 2022-10-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'seller'), ('2', 'customer')], default='', max_length=50),
        ),
    ]
