# Generated by Django 3.2.1 on 2022-10-28 21:24

import api.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_usercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=api.products.models.upload_path),
        ),
    ]
